config/routes.rb
Rails.application.routes.draw do
  resources :pucharses
  resources :profiles
  devise_for :users
  resources :products
  resources :products

  root 'pucharses#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :pucharses
  validates_presence_of :name, :age
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = current_user.build_profile(profile_params)

    respond_to do |format|
      if @profile.save
          if current_user.profile.is_admin
            format.html { redirect_to profiles_url, notice: 'Perfil criado com sucesso.' }
          else
            format.html { redirect_to pucharses_path, notice: 'Perfil criado com sucesso.' }
          end
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Perfil alterado com sucesso.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      if current_user.profile 
        format.html { redirect_to profiles_url, notice: 'Usuário excluído com sucesso.' }
      else
        format.html { redirect_to pucharses_path, notice: 'Usuário excluído com sucesso.' }
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def is_admin?
      profile.is_admin
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :is_admin, :age, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li class="alert alert-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label><strong>Nome</strong></label>
    <%= f.text_field :name, class: "form-control", placeholder: "Ex. João" %>
    <% if current_user.profile && current_user.profile.is_admin %>
      <small class="form-text text-muted">Primeiro nome do usuário.</small>
    <% else %>
      <small class="form-text text-muted">Insira seu <strong>primeiro</strong> nome.</small>
    <% end %>
  </div>

  <div class="form-group">
    <label><strong>Idade</strong></label>
    <%= f.number_field :age, class: "form-control", placeholder: "Ex. 23" %>
    <% if current_user.profile && current_user.profile.is_admin %>
      <% if @profile.name %>
        <small class="form-text text-muted">Quantos anos <strong><%= @profile.name %></strong> tem.</small>
      <% else %>
        <small class="form-text text-muted">A idade do usuário.</small>
      <% end %>
    <% else %>
      <small class="form-text text-muted">Quantos anos você tem.</small>
    <% end %>
  </div>

  <div class="custom-control custom-checkbox text-center">
    <%= f.check_box :is_admin, class: "custom-control-input", id: "admin_check" %>
    <label class="custom-control-label" for="admin_check">Administrador</label>
  </div>
  <% if current_user.profile && current_user.profile.is_admin %>
    <small id="emailHelp" class="form-text text-muted text-center">Fazer deste usuário um <strong>administrador</strong>.</small>
  <% else %>
    <small id="emailHelp" class="form-text text-muted text-center">Se é ou não <strong>administrador</strong>.</small>
  <% end %>

  <br>
  <% if current_user.profile && current_user.profile.is_admin %>
    <%= f.submit "Salvar", class: "btn btn-block btn-lg btn-success" %>
  <% else %>
    <%= f.submit "Vamos lá!", class: "btn btn-block btn-lg btn-success" %>
  <% end %>
<% end %>

app/views/profiles/edit.html.erb
<div class="profile-container">

    <% if current_user.profile.is_admin %>
        <h1 class="text-center">Editar perfil</h1>
        <h6 class="text-center text-muted">Aqui você pode alterar o perfil.</h6>
    <% else %>
        <h1 class="text-center">Editar meu perfil</h1>
        <h6 class="text-center text-muted">Aqui você pode fazer a alteração que achar necessária em seu perfil.</h6>
    <% end %>

    <br>
    <div class="card">
        <div class="card-body">
            <%= render 'form' %>  

            <br>
            <% if current_user.profile.is_admin  %>
                <%= link_to 'Voltar', profiles_path, class: "btn btn-block btn-light" %>
            <% else %>
                <%= link_to 'Voltar', profile_path(current_user.profile), class: "btn btn-block btn-light" %>
            <% end %>
        </div>
    </div>  
</div>

app/views/profiles/index.html.erb
<% if notice %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<strong class="text-muted">Administrador</strong>
<h1>Usuários</h1>
<h6 class="text-muted">Aqui você está a lista de todos os usuários da aplicação.</h6>

<br>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Nome</th>
      <th>Idade</th>
      <th>Acesso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td class="text-muted"><%= profile.id %></td>
        <td><%= profile.name %></td>
        <td><%= profile.age %> anos</td>
        <td>
          <% if profile.is_admin %>
            <h5><span class="badge badge-dark">Administrador</span></h5>
          <% end %>
        </td>
        <td><%= link_to 'Ver', profile, class: "btn btn-block btn-outline-info" %></td>
        <td><%= link_to 'Editar', edit_profile_path(profile), class: "btn btn-block btn-outline-secondary" %></td>
        <td><%= link_to 'X', profile, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn  btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/profiles/new.html.erb
<div class="profile-container">

    <% if current_user.profile && current_user.profile.is_admin %>
        <h1 class="text-center">Novo perfil</h1>
        <h6 class="text-center text-muted">Aqui você pode criar um novo usuário e defini-lo com administrador.</h6>
    <% else %>
        <h1 class="text-center">Bem-vindo!</h1>
        <h6 class="text-center text-muted">Para começar, vamos criar seu perfil.</h6>
    <% end %>

    <br>
    <div class="card">
        <div class="card-body">
            <%= render 'form' %>

            <br>
            <% if current_user.profile %>
                <%= link_to 'Voltar', pucharses_path, class: "btn btn-block btn-light" %>
            <% end %>
        </div>
    </div>
</div>

app/views/profiles/show.html.erb
<div class="profile-container">
  
  <% if notice %>
    <p id="notice" class="alert alert-success"><%= notice %></p>
  <% end %>

  <% if current_user.profile.is_admin %>
    <h1 class="card-title text-center">Perfil</h1>
    <h6 class="card-subtitle mb-2 text-muted text-center">Todos os dados de <%= @profile.name %> que conseguimos encontrar.</h6>
  <% else %>
    <h1 class="card-title text-center">Meu perfil</h1>
    <h6 class="card-subtitle mb-2 text-muted text-center">Aqui você encontra todas as informações sobre nossa pessoa mais importante. <strong>Você</strong>!</h6>
  <% end %>

  <br>
  <div class="card">
    <div class="card-body">

      <div class="form-group">
        <label><strong>Nome</strong></label><br>
        <%= @profile.name %>
      </div>

      <div class="form-group">
        <label><strong>Idade</strong></label><br>
        <%= @profile.age %> anos
      </div>

      <div class="form-group">
        <label><strong>E-mail</strong></label><br>
        <%= @profile.user.email  %>
      </div>

      <% if @profile.is_admin %>
        <h4 class="text-center"><span class="badge badge-pill badge-dark">É um administrador</span></h4>
      <% end %>
      
      <br>
      <%= link_to 'Editar', edit_profile_path(@profile), class: "btn btn-block btn-secondary" %>
      <% if current_user.profile.is_admin %>
        <%= link_to 'Voltar', profiles_path, class: "btn btn-block btn-light" %>      
      <% else %>
        <%= link_to 'Voltar', pucharses_path, class: "btn btn-block btn-light" %>      
      <% end %>

    </div>
  </div>
</div>