config/routes.rb
Rails.application.routes.draw do
  resources :pucharses
  resources :profiles
  devise_for :users
  resources :products
  resources :products

  root 'pucharses#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Compras | Pós</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in?  %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">

      <% if current_user.profile %>
      <a class="navbar-brand">Compras</a>
      <div class="collapse navbar-collapse">
        <div class="navbar-nav">
          <%= link_to 'Minhas compras', pucharses_path, class: 'nav-item nav-link' %>
          <% if current_user.profile && current_user.profile.is_admin %>
            <%= link_to 'Produtos', products_path, class: 'nav-item nav-link' %>
            <%= link_to 'Usuários', profiles_path, class: 'nav-item nav-link' %>
          <% end %>
        </div>
      </div>

      <div class="nav justify-content-end">

          <div class="btn-group dropleft">
            <a class="btn" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.profile.name  %>
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <%= link_to 'Meu perfil', profile_path(current_user.profile), class: "dropdown-item"  %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Minhas compras', pucharses_path, class: "dropdown-item"  %>
              <% if current_user.profile && current_user.profile.is_admin %>
                <%= link_to 'Produtos', products_path, class: "dropdown-item" %>
                <%= link_to 'Usuários', profiles_path, class: "dropdown-item" %>
              <% end %>        
              <div class="dropdown-divider"></div>
              <%= link_to('Sair', destroy_user_session_path, method: :delete, class: "dropdown-item logout_button") %>
            </div>
          </div>

      </div>
    <% else %>
      <a class="navbar-brand">Seja bem vindo ao <strong>Compras</strong>!</a>
    <% end %>
  </nav>
<% end %>

<div class="container" role="main">
  <%= yield %>
</div>

</body>
</html>